services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: django_backend_tt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=django_backend_tt
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DEBUG=True
      - SECRET_KEY=your-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: