# Generated by Django 6.0.5 on 2026-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("user", "Пользователь"),
                            ("guest", "Гость"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
    ]
