# Generated by Django 6.0.5 on 2026-05-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRoleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(default=False, verbose_name="Чтение своего"),
                ),
                (
                    "read_all",
                    models.BooleanField(default=False, verbose_name="Чтение всего"),
                ),
                ("create", models.BooleanField(default=False, verbose_name="Создание")),
                (
                    "update",
                    models.BooleanField(default=False, verbose_name="Изменение своего"),
                ),
                (
                    "update_all",
                    models.BooleanField(default=False, verbose_name="Изменение всего"),
                ),
                (
                    "delete",
                    models.BooleanField(default=False, verbose_name="Удаление своего"),
                ),
                (
                    "delete_all",
                    models.BooleanField(default=False, verbose_name="Удаление всего"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rule",
                        to="roles.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило доступа",
                "verbose_name_plural": "Правила доступа",
            },
        ),
    ]
