# Generated by Django 6.0.5 on 2026-05-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0002_accessrolerule"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Элемент"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бизнес-элемент",
                "verbose_name_plural": "Бизнес-элементы",
            },
        ),
        migrations.AddField(
            model_name="accessrolerule",
            name="element",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="roles.businesselement",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="accessrolerule",
            unique_together={("role", "element")},
        ),
    ]
